### ISSUE TITLE
What is the intended meaning of isVariant?

### ISSUE THREAD

**Issue by htvennik** [trishume/ddbus#22]
Current implementation effectively defines it as meaning `isInstanceOf!(ddbus.thin.Variant, T)`.

Currently I am working of a PR implementing support for Phobos-style variant types. Now I wonder if e.g. `isVariant!(std.variant.Algebraic!(int, double, string))` should evaluate to `true`.

**EDIT:** _Sorry, posted from wrong account..._

**Comment by WebFreak001** [comment]
right now `isVariant` should only return true for the `std.variant.Variant` because of the implementation ([here](https://github.com/trishume/ddbus/blob/a737496d37e237e2c7021f42381f8b96fca8a39d/source/ddbus/util.d#L19), [here](https://github.com/trishume/ddbus/blob/a737496d37e237e2c7021f42381f8b96fca8a39d/source/ddbus/conv.d#L111) and [here](https://github.com/trishume/ddbus/blob/a737496d37e237e2c7021f42381f8b96fca8a39d/source/ddbus/conv.d#L176)), though you could change the implementation and then change the template too, but because it is public we should probably make it private first. It might break user code but I don't think anyone using ddbus should use it for its `isVariant` function.

**Comment by thaven** [comment]
Yes, I noticed that some code needs modification if `isVariant` is changed. I also agree that user code generally shouldn't use `isVariant` directly.

Nonetheless, making it non-public breaks backwards compatibility. Lack of documentation renders undefined whether updating the template to return `true` for Phobos-style variants is a backwards compatibility break.

At this moment I'd like to keep backwards compatibility as much as possible while adding features. But surely some stuff can be improved, and BC breaks will be inevitable in that process. Currently I am waiting for Phobos 2.076, which I expect to include a recently accepted PR of mine that will help take ddbus to a whole new level. And I think that would be the time to do any potentially breaking changes and head for v3.0.0.

For now I suggest keeping `isVariant` as is, but deprecating it, and thus update any dependent code anyway (replacing it by `isInstanceOf!(Variant, ...)`).
