### ISSUE TITLE
Where is the documentation of Get?

### ISSUE THREAD

**Issue by adnan449** [trishume/ddbus#47]
I would like to get the property `Drive` from `org.freedesktop.UDisks2.Block`. I want to filter the ones that are not removable media.

 I am trying to use `Get` as in the readme but I am not having any luck.

```d
import std.stdio, ddbus;
import ddbus : Variant;
import ddbus.c_lib;
import std.conv: to;

void main()
{
	Connection conn = connectToBus(DBusBusType.DBUS_BUS_SYSTEM);
	PathIface obj = new PathIface(conn, busName("org.freedesktop.UDisks2"),
			ObjectPath("/org/freedesktop/UDisks2/Manager"),
			interfaceName("org.freedesktop.UDisks2.Manager"));

	Variant!DBusAny[string] arg;
	foreach (device; obj.call!(ObjectPath[])("GetBlockDevices", arg))
	{
		///org/freedesktop/UDisks2/block_devices/sda3
		writeln(obj.Get(device, "Drive").to!ObjectPath());
	}
}
```

>ddbus.exception.DBusException@../../.dub/packages/ddbus-3.0.0-beta.1/ddbus/source/ddbus/thin.d(931): No such method “Get”

How can I use Get to get properties? Looking for the symbol is not helping (https://github.com/trishume/ddbus/search?q=Get&unscoped_q=Get)

**Comment by WebFreak001** [comment]
`Get` isn't actually implemented in ddbus, it's a standard dbus interface, see https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties

The `.Get` method you are trying to call is actually just syntactic sugar for `obj.call!ObjectPath("Get", device, "Device")`

I believe `device` isn't the correct parameter you want to pass because it's a ObjectPath but in the documentation it says it should be an interface name.

Maybe you want to actually call `.Get` on another PathIface with your object path as path? Something like
```d
	Connection conn = connectToBus(DBusBusType.DBUS_BUS_SYSTEM);
	PathIface obj = new PathIface(conn, busName("org.freedesktop.UDisks2"),
			ObjectPath("/org/freedesktop/UDisks2/Manager"),
			interfaceName("org.freedesktop.UDisks2.Manager"));

	Variant!DBusAny[string] arg;
	foreach (devicePath; obj.call!(ObjectPath[])("GetBlockDevices", arg))
	{
		PathIface device = new PathIface(conn,
			busName("org.freedesktop.UDisks2"),
			devicePath,
			interfaceName("org.freedesktop.DBus.Properties"));
		///org/freedesktop/UDisks2/block_devices/sda3
		writeln(device.Get("", "Drive").to!ObjectPath());
	}
```
